name: Reproduce Error

on:
  push:
    branches: 
      - "main"

  workflow_dispatch:

jobs:
  reproduce_error:
    runs-on: 'ubuntu-22.04'
    container:
      image: 'ubuntu:22.04'
    steps:
      - name: install dependencies
        run: |
          apt-get update -y
          
          # install docker following https://docs.docker.com/engine/install/ubuntu/
          apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update -y
          apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
          
          apt-get install -y jq
      - name: reproduce error
        run: |
          docker run -d --rm --name tmp -p 8080:8080 hashicorp/http-echo -listen=:8080 -text="hello world"
          docker container inspect tmp | jq -r '.[0].NetworkSettings.Networks.bridge.IPAddress'
          set -x
          # localhost
          curl -sS localhost:8080 || true
          # docker host
          curl -sS tmp:8080 || true
          # docker ip
          curl -sS $(docker container inspect tmp | jq -r '.[0].NetworkSettings.Networks.bridge.IPAddress'):8080 || true
          docker ps
          docker stop tmp
          set +x
